version: 2.1

jobs:
  build:
    working_directory: ~/recipe-project
    docker:
      # Primary container image where all steps run
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore-cache:
          key: recipe-project-{{ checksum "pom.xml" }}
            - run: mvn install -D skipTests
            - run: mvn dependency:go-offline
            - save_cache:
              paths:
                - ~/.m2
      - key: recipe-project-{{ checksum "pom.xml" }}
          - run: mvn package
          - store_test_results:
              path: target/surefire-reports
                - store_artifacts:
                  path: target/recipe-project-0.0.1-SNAPSHOT.jar