version: 2
jobs:
build:
working_directory: ~/spring5-recipe-app
docker:
  - image: circleci/openjdk:11-jdk
steps:
  - checkout
  - restore_cache:
keys:
    - key: spring5-recipe-app-{{ checksum "pom.xml" }}
       - run: mvn install -DskipTests
       - run: mvn dependency:go-offline
       - save_cache:
      paths:
        - ~/.m2
    - key: spring5-recipe-app-{{ checksum "pom.xml" }}
        - run: mvn package
        - store_test_results:
        path: target/surefire-reports
                - store_artifacts:
        path: target/spring5-recipe-app-0.0.1-SNAPSHOT.jar